language: go # 声明构建语言环境
sudo: false # 开启基于容器的Travis CI任务，让编译效率更高。

notifications: # 每次构建的时候是否通知，如果不想收到通知，那就设置false吧(email: false)
  email:
    recipients:
    - hexileee@gmail.com
  on_success: change
  on_failure: always

go:
- "1.11"

install:
- go build
- go get github.com/mattn/goveralls


script: # 集成脚本
- go test -bench=.
- go test ./... -v -cover -race -coverprofile=go.coverprofile
- goveralls -coverprofile=go.coverprofile -service=travis-ci -repotoken=$COVERALLS_TOKEN

after_success:
- bash <(curl -s https://codecov.io/bash)

env: #env环境变量设置，travis提供的repo_token安全方式
  global:
    secure: "ByMaf0uFvhrBL98sgGAuEBzhsc5Hf07+Mj1h6wSQliG/ivG+3ne898G3kWyTG0X9m6EScpEE+CuSyjHOxShtRbI5pJA3MHh2wMP92jCcq1IZ0cRGxBaN3bBAcTwY5s+JtQR+lNsTnYgFa4LaGn204wG2FRgbXWSP7TkkXsDfdAtBZdo0nhulkhGR24TsU7Fc7TN2EApjZHku8fQajqDrmk1yOb1DWc+c5yvWa0OJITyhCKdZimtTpD9HinYQ+RAr4mRupQ71gGaMuN/IslJvy8j1EjLQjEsHM3lEF7iidLL2mAYvozUtEzDhbpXd4BVwvUaWDJhS8kiLoc09jDa7tyUkH/tCPam6cfvxHqA7DgiJK1wqlaQMxwzz7XLfWIB5xuqH/Cnq5Ahh/Uyn6pkwI/Q1feKDxQyxu/ozTV/infv1Cc5Fhbd3TRoZ9anyClamGYtYwVJ/RljYPuAfzF4KIFM3/YOAEpZW+IvWZU+7Mw5lKMGJatuDBASQC4zNkQCCC3WNEUQIZbLIL5rVMg9Y0PNw1n1WAB8Xk3JxlJXzUwirXvXpIPIBW5/5hFxCU3UAXQhr0JlXhkkNVnhuJU94lcHV1PEDfVoU8N3ET5112gwBFY7OHeFGHou9XM0+gDVYSxiqZvftwZqaARWv2tyYUl3uFvXmlXsGCdfgcAQmJek="
